### ISSUE TITLE
Usage of dagster-pandas

### ISSUE THREAD

**Issue by martimpassos** [pybokeh/dagster-sklearn#1]
Hi @pybokeh, thank you so much for this repo. It may be simple but it has _really_ helped me understand/define a project structure using Dagster and Docker. They should have something like this in their examples/tutorials! 

Anyway, I'm curious about your application of dagster-pandas in the project. I see you install it but it doesn't seem to appear anywhere else in the code. Is this something you plan on using in the future? As I understand it helps validating your columns data and types.

**Comment by pybokeh** [comment]
Hello @martimpassos !  I'm glad this repo helped you.  I agree that there should be intermediate level examples as I struggled early on trying to learn to use dagster.  They made changes to their documentation recently, but to be honest, I have not looked for changes in their examples or tutorials as I've somewhat have a good feel on using dagster now.  But I know I am still using just a tiny fraction of all that is available in dagster.  I should probably review the new documentation examples and provide feedback.

As far as dagster_pandas, it was a mistake on my part to include it as I do not intend to use dagster_pandas in this repo.  I do use it for my projects at work (column and data type validation, although looking to transition to using [great expectations](https://github.com/great-expectations/great_expectations) library) and so I accidentally included it in this repo out of habit.
