### ISSUE TITLE
Another example

### ISSUE THREAD

**Issue by AntonFriberg** [pybokeh/dagster-sklearn#2]
Hi! Thanks a lot for this example. I like your organization of the different Dagster resources into their own folders.

I constructed my own example based on the Dagster tutorial that provides a more bare-bones example that can be run both in a local Python environment and using Docker-Compose.

I referenced this repo in the README and hope that it is OK?

https://github.com/AntonFriberg/dagster-project-example

**Comment by pybokeh** [comment]
Hello!  That is an awesome, clean example.  Yes, totally fine with me!
